[program:kisansmart]
directory=/home/kisansmart/kisan-smart
command=/home/kisansmart/kisan-smart/venv/bin/gunicorn -w 4 --worker-class gevent --bind 127.0.0.1:8000 --timeout 120 'app:create_app()'

user=kisansmart
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true

# Logging
stderr_logfile=/var/log/kisansmart/supervisor_err.log
stdout_logfile=/var/log/kisansmart/supervisor_out.log
stderr_logfile_maxbytes=10MB
stdout_logfile_maxbytes=10MB
